---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "Europe/Amsterdam"
    commit-message:
      prefix: "dependabot"
    labels:
      - "auto-merge"
      - "dependencies"
