---
name: "❓ Ask for help"
description: "Submit a question related to this repository."
# title: "[Help]: <Brief description of the issue> "
labels: [help]
body:
  - type: checkboxes
    id: duplicate-check
    attributes:
      label: "⚠️ Please verify that this question has NOT been raised before"
      description:
        "Ensure this question has not already been raised. Use [this
        link](https://github.com/homelab-alpha/shell-script/issues?q=) to
        search."
      options:
        - label: "I confirm that no similar issue exists."
          required: true
  - type: checkboxes
    id: security-policy-agreement
    attributes:
      label: "🛡️ Security Policy Agreement"
      description:
        "Please confirm that you have read the [Security
        Policy](https://github.com/homelab-alpha/shell-script/security/policy)
        before reporting security-related issues."
      options:
        - label: "I have read and agree to the Security Policy."
          required: true
  - type: textarea
    id: problem-description
    validations:
      required: true
    attributes:
      label: "📝 Describe your problem"
      description:
        "Provide a detailed explanation of your issue or question. Include steps
        to reproduce, screenshots, or any relevant details."
      placeholder: "Describe your question or problem in detail."
  - type: textarea
    id: attempted-solutions
    validations:
      required: true
    attributes:
      label: "🔍 Attempted Solutions"
      description:
        "List the steps you've taken to troubleshoot the issue or answer your
        question. Include both successful and unsuccessful attempts."
      placeholder: "List all the actions you've tried to address the issue."
  - type: textarea
    id: logs-or-errors
    validations:
      required: false
    attributes:
      label: "📜 Logs or Error Messages"
      description:
        "Share any logs or error messages related to your issue, if available."
  - type: textarea
    id: relevant-config-files
    validations:
      required: false
    attributes:
      label: "⚙️ Relevant Configuration Files"
      description:
        "Attach any relevant configuration files or code snippets that might
        help diagnose the issue. Use backticks (```) for formatting if pasting
        directly."
      placeholder:
        "Paste or upload your configuration files/code snippets here."
  - type: textarea
    id: dependencies-info
    validations:
      required: true
    attributes:
      label: "📂 Dependencies and Versions"
      description:
        "List all dependencies and their versions used in your setup. This
        information helps identify compatibility issues."
      placeholder: "e.g., Library X v1.2.3, Library Y v4.5.6"
  - type: input
    id: software-version
    validations:
      required: true
    attributes:
      label: "📦 Software Version"
      description:
        "Specify the version of the software you are using. Avoid using vague
        terms like 'latest' or 'current'."
      placeholder: "e.g., 1.10.0"
  - type: input
    id: operating-system
    validations:
      required: true
    attributes:
      label: "💻 Operating System"
      description:
        "Provide the details of the operating system and architecture you are
        using."
      placeholder:
        "e.g., Ubuntu Server 24.04.1 LTS (GNU/Linux 6.8.0-48-generic x86_64)"
  - type: input
    id: browser-info
    validations:
      required: false
    attributes:
      label: "🌐 Browser Information"
      description:
        "If applicable, specify the browser and version you are using."
      placeholder:
        "e.g., Brave Version 1.73.101 Chromium: 131.0.6778.139 (Official Build)
        (64-bit)"
  - type: textarea
    id: environment-details
    validations:
      required: true
    attributes:
      label: "🖥️ Environment Details"
      description: |
        Provide detailed information about your setup to help us understand your environment better:
          - **Hosting Environment**: Are you running this on a local machine, cloud provider (AWS, Azure, etc.), or other platforms?
          - **Runtime Details**: Specify the runtime environment, such as Docker, Kubernetes, Node.js, etc.
          - **Database Configuration**: Mention the type of database (e.g., SQLite, MariaDB, PostgreSQL) and any relevant configurations.
          - **Storage Details**: Describe the file system or storage setup used (e.g., ext4, NTFS, ZFS, NFS).
          - **Additional Context**: Other context that might affect the issue.
      value: |
        - Hosting Environment:
        - Runtime Details:
        - Database Configuration:
        - Storage Details:
        - Additional Context:
