---
exclude_paths:
parseable: true
quiet: true
rulesdir:
skip_list:
  - "empty-string-compare"
  - "204"
  - "no-changed-when"
  - "command-instead-of-module"
  - "command-instead-of-shell"
  - "no-handler"
  - "unnamed-task"
  - "yaml"
tags:
use_default_rules: true
verbosity: 1
