---
MD004: false
MD007:
  indent: 2
MD013:
  line_length: 80,
  code_block_line_length: 120,
  tables: false
MD026:
  punctuation: ".,;:!。，；:"
MD029: false
MD033: false
MD036: false
MD041: false
blank_lines: false
no-hard-tabs: false
